### ISSUE TITLE
Docker enable hostname and port endpoint. Fix multiple bugs. Add timeouts mysql connection and keystone endpoint. Optimize image size

### ISSUE THREAD

**Issue by cesarjorgemartinez** [telefonicaid/fiware-keystone-spassword#40]
- Docker enable hostname and port endpoint. Cases (optional port): -dbhost hostname[:port]

- Add optional timeout DBTIMEOUT if no mysql connection. Default to 60 seconds

- Fix keystone root password: Use MySQL in docker container or external without security risk root access. Only is permitted in external: create a database and set grants to user keystone "%" and localhost.

- Fix error when change to liberty keystone "Invalid credentials":
  When we do a initial installation then fails with a strange error: "Invalid OpenStack Identity credentials"
  Analysis: The environment variables for use keystone has changed
  Test: Enter inside container and set actual variables:
  KEYSTONE_ADMIN_PASSWORD=4pass1w0rd
  export OS_SERVICE_TOKEN=${KEYSTONE_ADMIN_PASSWORD}
  export OS_SERVICE_ENDPOINT=http://127.0.0.1:35357/v2.0
  keystone user-list (then fail with "Invalid OpenStack Identity credentials"
  Proposed solution: Change OS_SERVICE_TOKEN by SERVICE_TOKEN and OS_SERVICE_ENDPOINT by SERVICE_ENDPOINT in all places where they appear
  Reference: https://ask.openstack.org/en/question/11643/how-to-solve-keystone-errorexpecting-an-auth-url-via-either-os-auth-url-or-envos_auth_url-on-havana/

- Fix error Fedora has changed link URL RPM for liberty to https://repos.fedorapeople.org/openstack/EOL/openstack-liberty/rdo-release-liberty-5.noarch.rpm

- Fix error when change to liberty keystone "Unable to establish connection...":
  When we do a initial installation then sometimes the entrypoint tasks fails because the keystone-all takes too long to start (More than 5 seconds). Then see a strange error: "Unable to establish connection to http://127.0.0.1:35357/v2.0/users"
  Solution: Change all "sleep 5" to timeouts using DBTIMEOUT

- Add explain for all keystone commands in files docker/postlaunchconfig*.sh for tracing and facility (echo "INFO: We do xyz")

- Create user keystone as its password provided, not "keystone", and use os_service_token as provided

- Optimize image size

Uploaded fix to dockerhub with tag fixissue40

This issue depends on: https://github.com/telefonicaid/fiware-keypass/issues/104. Need to merge the associated PR before merge the associated PR of this issue.

Docker compose file tests:
```yaml
mongo:
  image: mongo:3.2

orion:
  image: telefonicaiot/fiware-orion
  links:
    - mongo
  ports:
    - "10026:1026"
  command: -dbhost mongo

mysql:
  image: mysql:5.5  
  expose:
    - "3306"
  ports:
    - "3306:3306"
  environment:
    MYSQL_ROOT_PASSWORD: iotonpremise
    MYSQL_DATABASE: keypass
    MYSQL_USER: keypass
    MYSQL_PASSWORD: keypass

keypass:
#  image: telefonicaiot/fiware-keypass
  image: telefonicaiot/fiware-keypass:fixissue104
  links:
    - mysql
  expose:
    - "17070"
    - "7071"
  ports:
    - "17070:7070"
    - "7071:7071"
  command: -dbhost mysql[:3306]
[  environment:
    - DBTIMEOUT=200]

keystone:
#  image: telefonicaiot/fiware-keystone-spassword
  image: telefonicaiot/fiware-keystone-spassword:fixissue40
  expose:
    - "5001"
  links:
    - mysql
  ports:
    - "5001:5001"
  command: -dbhost mysql[:3306] -default_pwd 4pass1w0rd -mysql_pwd iotonpremise
[  environment:
    - DBTIMEOUT=200]

orchestrator:
  image: telefonicaiot/orchestrator
  expose:
    - "8084"
  links:
    - keystone
    - keypass
    - orion
  ports:
    - "8084:8084"
  command: -keystonehost keystone -keypasshost keypass -orionhost orion

portal:
  image: telefonicaiot/portal
  links:
    - keystone
    - orion
    - orchestrator
  ports:
    - "80:80"
    - "8008:8008"
    - "443:443"
  environment:
    - portal_hostname=my_iot_portal
  command: -urlcep localhost:9090 -urlidm keystone:5001 -urlcb orion:1026 -urlorc orchestrator:8084 -urliot localhost:8081 -urlsth localhost:8666
```
